spring:
  datasource:
    url: jdbc:postgresql://dpg-d0ieq3je5dus73drhev0-a.oregon-postgres.render.com:5432/carrinho
    username: ${db_username}
    password: ${db_senha}

    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
