spring:
  datasource:
    url: jdbc:postgresql://dpg-d0ieq3je5dus73drhev0-a.oregon-postgres.render.com:5432/carrinho
    username: andrew
    password: 8crJLn27XS4U87m4EjrPt67ulV26L3eb

    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
